/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import Model.Database;
import Model.HandlerComponent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author REDHAT
 */
public class Laporan extends javax.swing.JFrame {
    int mosX, mosY;
    Boolean periode = false;
    Database db = new Database();
    String nmLaporan = "";
    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    void printLaporan() throws SQLException{
        Model.HandlerComponent.Report jReport = new HandlerComponent.Report();
        if(restock.isSelected()) {
            nmLaporan = "REPORT_HeadReInvent";
            jReport.setParam("Tahun", Integer.valueOf(tahun.getText()));
            jReport.setParam("Bulan", bulan.getSelectedIndex()+1);
            jReport.setParam("KodeSupplier", JOptionPane.showInputDialog("Masukkan Kode Supplier\n*note : kosongkan untuk print semua"));
        }
        if(dataBarang.isSelected()) {
            nmLaporan = "REPORT_Inventory";
            
        }
        if(dataSupplier.isSelected()) {
            nmLaporan = "REPORT_Supplier";
        }
        if(dataPesanan.isSelected()) {
            nmLaporan = "REPORT_Order";
            
        }
        jReport.setFileName(nmLaporan);
        jReport.printReport();
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipeLaporan = new javax.swing.ButtonGroup();
        panelGradient1 = new Model.PanelGradient();
        jLabel1 = new javax.swing.JLabel();
        pnlTipeLaporan = new javax.swing.JPanel();
        dataBarang = new javax.swing.JRadioButton();
        dataPesanan = new javax.swing.JRadioButton();
        restock = new javax.swing.JRadioButton();
        dataSupplier = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        btnClose = new javax.swing.JLabel();
        pnlPeriode = new javax.swing.JPanel();
        cbTahun = new javax.swing.JCheckBox();
        cbBulan = new javax.swing.JCheckBox();
        tahun = new javax.swing.JTextField();
        bulan = new javax.swing.JComboBox<>();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MakanDong | Laporan");
        setUndecorated(true);
        setResizable(false);

        panelGradient1.setBackground(new java.awt.Color(82, 187, 239));
        panelGradient1.setGradientBackgroundColor(new java.awt.Color(255, 175, 16));
        panelGradient1.setGradientFocus(1000);
        panelGradient1.setMaximumSize(new java.awt.Dimension(639, 435));
        panelGradient1.setMinimumSize(new java.awt.Dimension(639, 435));
        panelGradient1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelGradient1MouseDragged(evt);
            }
        });
        panelGradient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelGradient1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icon/128/report128.png"))); // NOI18N

        pnlTipeLaporan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jenis Laporan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18), new java.awt.Color(0, 51, 51))); // NOI18N
        pnlTipeLaporan.setOpaque(false);

        tipeLaporan.add(dataBarang);
        dataBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataBarang.setForeground(new java.awt.Color(255, 255, 255));
        dataBarang.setText("Data Barang");
        dataBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        dataBarang.setOpaque(false);

        tipeLaporan.add(dataPesanan);
        dataPesanan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataPesanan.setForeground(new java.awt.Color(255, 255, 255));
        dataPesanan.setText("Pesanan");
        dataPesanan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        dataPesanan.setOpaque(false);

        tipeLaporan.add(restock);
        restock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        restock.setForeground(new java.awt.Color(255, 255, 255));
        restock.setText("Restok Barang");
        restock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        restock.setOpaque(false);
        restock.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                restockItemStateChanged(evt);
            }
        });

        tipeLaporan.add(dataSupplier);
        dataSupplier.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dataSupplier.setForeground(new java.awt.Color(255, 255, 255));
        dataSupplier.setText("Data Supplier");
        dataSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        dataSupplier.setOpaque(false);

        javax.swing.GroupLayout pnlTipeLaporanLayout = new javax.swing.GroupLayout(pnlTipeLaporan);
        pnlTipeLaporan.setLayout(pnlTipeLaporanLayout);
        pnlTipeLaporanLayout.setHorizontalGroup(
            pnlTipeLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipeLaporanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlTipeLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataBarang)
                    .addComponent(restock))
                .addGap(48, 48, 48)
                .addGroup(pnlTipeLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataSupplier)
                    .addComponent(dataPesanan))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlTipeLaporanLayout.setVerticalGroup(
            pnlTipeLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTipeLaporanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlTipeLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataBarang)
                    .addComponent(dataPesanan))
                .addGap(22, 22, 22)
                .addGroup(pnlTipeLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restock)
                    .addComponent(dataSupplier))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Laporan");

        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icon/32/cancel32.png"))); // NOI18N
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        pnlPeriode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Periode Laporan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 18), new java.awt.Color(0, 0, 51))); // NOI18N
        pnlPeriode.setEnabled(false);
        pnlPeriode.setOpaque(false);

        cbTahun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbTahun.setForeground(new java.awt.Color(255, 255, 255));
        cbTahun.setText("Tahun");
        cbTahun.setContentAreaFilled(false);
        cbTahun.setEnabled(false);
        cbTahun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTahunItemStateChanged(evt);
            }
        });

        cbBulan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbBulan.setForeground(new java.awt.Color(255, 255, 255));
        cbBulan.setText("Bulan");
        cbBulan.setContentAreaFilled(false);
        cbBulan.setEnabled(false);

        tahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tahun.setText("2020");
        tahun.setEnabled(false);
        tahun.setMargin(new java.awt.Insets(2, 5, 2, 2));
        tahun.setNextFocusableComponent(bulan);

        bulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bulan.setMaximumRowCount(4);
        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "Desember" }));
        bulan.setEnabled(false);
        bulan.setOpaque(false);

        javax.swing.GroupLayout pnlPeriodeLayout = new javax.swing.GroupLayout(pnlPeriode);
        pnlPeriode.setLayout(pnlPeriodeLayout);
        pnlPeriodeLayout.setHorizontalGroup(
            pnlPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeriodeLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTahun)
                    .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPeriodeLayout.setVerticalGroup(
            pnlPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeriodeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTahun)
                    .addComponent(cbBulan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPeriodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tahun, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bulan))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnPrint.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Icon/32/printer32.png"))); // NOI18N
        btnPrint.setText("Lihat Laporan");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlPeriode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlTipeLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(32, 32, 32))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlTipeLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void cbTahunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTahunItemStateChanged
        if(!cbTahun.isSelected()){
            cbBulan.setEnabled(false); cbBulan.setSelected(false);
            bulan.setEnabled(false);
        }else{
            cbBulan.setEnabled(true); bulan.setEnabled(true);
        }
    }//GEN-LAST:event_cbTahunItemStateChanged

    private void panelGradient1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient1MouseDragged
        int coordX = evt.getXOnScreen(), coordY = evt.getYOnScreen();
        this.setLocation(coordX-mosX, coordY-mosY);
    }//GEN-LAST:event_panelGradient1MouseDragged

    private void panelGradient1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelGradient1MousePressed
        mosX = evt.getX();
        mosY = evt.getY();
    }//GEN-LAST:event_panelGradient1MousePressed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
            try {
                printLaporan();
            } catch(SQLException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void restockItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_restockItemStateChanged
        if(!restock.isSelected()) {
            pnlPeriode.setEnabled(false);
            cbTahun.setEnabled(false); cbBulan.setEnabled(false);
            tahun.setEnabled(false); bulan.setEnabled(false);
            periode = false;
        } else {
            pnlPeriode.setEnabled(true);
            cbTahun.setEnabled(true);
            tahun.setEnabled(true);
            periode = true;
        }
    }//GEN-LAST:event_restockItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JCheckBox cbBulan;
    private javax.swing.JCheckBox cbTahun;
    private javax.swing.JRadioButton dataBarang;
    private javax.swing.JRadioButton dataPesanan;
    private javax.swing.JRadioButton dataSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Model.PanelGradient panelGradient1;
    private javax.swing.JPanel pnlPeriode;
    private javax.swing.JPanel pnlTipeLaporan;
    private javax.swing.JRadioButton restock;
    private javax.swing.JTextField tahun;
    private javax.swing.ButtonGroup tipeLaporan;
    // End of variables declaration//GEN-END:variables
}
