/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

/**
 *
 * @author REDHAT
 */
public class MainMenu extends javax.swing.JFrame {
    Inventory frmInvent;
    Recipe frmRecipe;
    Order frmOrder;
    Supplier frmSupplier;
    
            
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOrderMenu = new javax.swing.JButton();
        btnInventMenu = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRecipeMenu = new javax.swing.JButton();
        btnSupplierMenu = new javax.swing.JButton();
        btnReportMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MakanDong | Main Menu");
        setResizable(false);

        btnOrderMenu.setText("Order");
        btnOrderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMenuActionPerformed(evt);
            }
        });

        btnInventMenu.setText("Inventory");
        btnInventMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventMenuActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");

        btnRecipeMenu.setText("Recipe");
        btnRecipeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecipeMenuActionPerformed(evt);
            }
        });

        btnSupplierMenu.setText("Supplier");
        btnSupplierMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierMenuActionPerformed(evt);
            }
        });

        btnReportMenu.setText("Laporan");
        btnReportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(btnInventMenu)
                    .addComponent(btnOrderMenu))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecipeMenu)
                    .addComponent(btnSupplierMenu)
                    .addComponent(btnReportMenu))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRecipeMenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnSupplierMenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOrderMenu)
                        .addGap(18, 18, 18)
                        .addComponent(btnInventMenu)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMenuActionPerformed
        frmOrder = new Order();
        frmOrder.setVisible(true);
    }//GEN-LAST:event_btnOrderMenuActionPerformed

    private void btnRecipeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipeMenuActionPerformed
        frmRecipe = new Recipe();
        frmRecipe.setVisible(true);
    }//GEN-LAST:event_btnRecipeMenuActionPerformed

    private void btnInventMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventMenuActionPerformed
        frmInvent = Inventory.getInstance();
        frmInvent.setVisible(true);
    }//GEN-LAST:event_btnInventMenuActionPerformed

    private void btnSupplierMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierMenuActionPerformed
        frmSupplier = new Supplier();
        frmSupplier.setVisible(true);
    }//GEN-LAST:event_btnSupplierMenuActionPerformed

    private void btnReportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventMenu;
    private javax.swing.JButton btnOrderMenu;
    private javax.swing.JButton btnRecipeMenu;
    private javax.swing.JButton btnReportMenu;
    private javax.swing.JButton btnSupplierMenu;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
