/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import Model.Database;
import Model.HandlerComponent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author REDHAT
 */
public class RecipeMaterial extends javax.swing.JDialog {
    Database db = new Database();
    DefaultTableModel tbModelRM = new DefaultTableModel();
    HandlerComponent hComp;
    ResultSet RSET;
    public Object[] DATA;
    /**
     * Creates new form RecipeMaterial
     */
    public RecipeMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initViewTable();
        this.setLocationRelativeTo(super.rootPane);
    }
    void initViewTable() {
        try {
            String SQL = "SELECT mCode, Deskripsi, Harga From material";
            hComp = new HandlerComponent();
            tbModelRM = hComp.initTable(tblDialMat, SQL, db, tbModelRM);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    void resetAll(){
        txPrice.setText(""); txDesc.setText(""); 
        txMCode.setText(""); txQty.setText("");
        tblDialMat.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDialMat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txMCode = new javax.swing.JTextField();
        txQty = new javax.swing.JTextField();
        btnAddtoRecipe = new javax.swing.JButton();
        txDesc = new javax.swing.JTextField();
        txPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Daftar Bahan Baku Resep");

        tblDialMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Bahan Baku", "Nama", "Harga/Satuan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDialMat.getTableHeader().setReorderingAllowed(false);
        tblDialMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDialMatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDialMat);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Bahan yg terpilih");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Jumlah Bahan");

        txMCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txMCode.setText("Code");
        txMCode.setEnabled(false);
        txMCode.setMargin(new java.awt.Insets(2, 7, 2, 7));

        txQty.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txQty.setText("0");
        txQty.setMargin(new java.awt.Insets(2, 7, 2, 7));
        txQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txQtyActionPerformed(evt);
            }
        });

        btnAddtoRecipe.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAddtoRecipe.setText("Tambahkan");
        btnAddtoRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoRecipeActionPerformed(evt);
            }
        });

        txDesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txDesc.setText("Description");
        txDesc.setEnabled(false);
        txDesc.setMargin(new java.awt.Insets(2, 7, 2, 7));

        txPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txPrice.setText("0");
        txPrice.setEnabled(false);
        txPrice.setMargin(new java.awt.Insets(2, 7, 2, 7));
        txPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnAddtoRecipe))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txMCode, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txQty)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(txPrice)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txMCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnAddtoRecipe)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDialMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDialMatMouseClicked
        if(evt.getClickCount() == 2 && !evt.isConsumed()) {
            txMCode.setText(tblDialMat.getValueAt(tblDialMat.getSelectedRow(), 0).toString());
            txDesc.setText(tblDialMat.getValueAt(tblDialMat.getSelectedRow(), 1).toString());
            txPrice.setText(String.valueOf(tblDialMat.getValueAt(tblDialMat.getSelectedRow(), 2)));            
        }
        if(evt.isConsumed())
            tblDialMat.clearSelection();
    }//GEN-LAST:event_tblDialMatMouseClicked

    private void btnAddtoRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoRecipeActionPerformed
        DATA = new Object[4];
        DATA[0] = txMCode.getText();
        DATA[1] = txDesc.getText();
        DATA[2] = Double.parseDouble(txQty.getText());
        DATA[3] = Double.valueOf(txPrice.getText());
        this.dispose();
    }//GEN-LAST:event_btnAddtoRecipeActionPerformed

    private void txQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txQtyActionPerformed

    private void txPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecipeMaterial dialog = new RecipeMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddtoRecipe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDialMat;
    private javax.swing.JTextField txDesc;
    private javax.swing.JTextField txMCode;
    private javax.swing.JTextField txPrice;
    private javax.swing.JTextField txQty;
    // End of variables declaration//GEN-END:variables
}
